// <auto-generated />
using System;
using KlangIT_V3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KlangIT_V3.Migrations
{
    [DbContext(typeof(ItLptWarehouseContext))]
    partial class ItLptWarehouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KlangIT_V3.Models.BorrowHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpectedReturnDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("HasExpectedReturnDate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPermanentBorrow")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReturn")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Itstaff")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ITStaff");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("RequestDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestSectionId")
                        .HasColumnType("int");

                    b.Property<string>("RequestUser")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RequestDepartmentId");

                    b.HasIndex("RequestSectionId");

                    b.ToTable("BorrowHistory", (string)null);
                });

            modelBuilder.Entity("KlangIT_V3.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("KlangIT_V3.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AssetId1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AssetId2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AssetId3")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AssetId4")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ItemBrandId")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ItemImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ItemModelId")
                        .HasColumnType("int");

                    b.Property<int>("ItemStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MinimumAmount")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AvailableAmount")
                        .HasColumnType("int");

                    b.Property<int>("BorrowedAmount")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemBrandId");

                    b.HasIndex("ItemModelId");

                    b.HasIndex("ItemStatusId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("KlangIT_V3.Models.ItemBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("ItemBrand", (string)null);
                });

            modelBuilder.Entity("KlangIT_V3.Models.ItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ItemBrandId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ItemBrandId");

                    b.ToTable("ItemModel", (string)null);
                });

            modelBuilder.Entity("KlangIT_V3.Models.ItemStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ItemStatus", (string)null);
                });

            modelBuilder.Entity("KlangIT_V3.Models.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("ItemType", (string)null);
                });

            modelBuilder.Entity("KlangIT_V3.Models.ItemTypeToBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemBrandId")
                        .HasColumnType("int");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemBrandId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("ItemTypeToBrand", (string)null);
                });

            modelBuilder.Entity("KlangIT_V3.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Section", (string)null);
                });

            modelBuilder.Entity("KlangIT_V3.Models.StockLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("LogNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NewStock")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfChange")
                        .HasColumnType("int");

                    b.Property<int>("OldStock")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RunningNo")
                        .HasColumnType("int");

                    b.Property<int>("StockLogTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("StockLogTypeId");

                    b.ToTable("StockLog", (string)null);
                });

            modelBuilder.Entity("KlangIT_V3.Models.StockLogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("StockLogType", (string)null);
                });

            modelBuilder.Entity("KlangIT_V3.Models.BorrowHistory", b =>
                {
                    b.HasOne("KlangIT_V3.Models.Item", "Item")
                        .WithMany("BorrowHistories")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_BorrowHistory_Item");

                    b.HasOne("KlangIT_V3.Models.Department", "RequestDepartment")
                        .WithMany("BorrowHistories")
                        .HasForeignKey("RequestDepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_BorrowHistory_Department");

                    b.HasOne("KlangIT_V3.Models.Section", "RequestSection")
                        .WithMany("BorrowHistories")
                        .HasForeignKey("RequestSectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_BorrowHistory_Section");

                    b.Navigation("Item");

                    b.Navigation("RequestDepartment");

                    b.Navigation("RequestSection");
                });

            modelBuilder.Entity("KlangIT_V3.Models.Item", b =>
                {
                    b.HasOne("KlangIT_V3.Models.ItemBrand", "ItemBrand")
                        .WithMany("Items")
                        .HasForeignKey("ItemBrandId")
                        .IsRequired()
                        .HasConstraintName("FK_Item_ItemBrand");

                    b.HasOne("KlangIT_V3.Models.ItemModel", "ItemModel")
                        .WithMany("Items")
                        .HasForeignKey("ItemModelId")
                        .IsRequired()
                        .HasConstraintName("FK_Item_ItemModel");

                    b.HasOne("KlangIT_V3.Models.ItemStatus", "ItemStatus")
                        .WithMany("Items")
                        .HasForeignKey("ItemStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Item_ItemStatus");

                    b.HasOne("KlangIT_V3.Models.ItemType", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Item_ItemType");

                    b.Navigation("ItemBrand");

                    b.Navigation("ItemModel");

                    b.Navigation("ItemStatus");

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("KlangIT_V3.Models.ItemModel", b =>
                {
                    b.HasOne("KlangIT_V3.Models.ItemBrand", "ItemBrand")
                        .WithMany("ItemModels")
                        .HasForeignKey("ItemBrandId")
                        .IsRequired()
                        .HasConstraintName("FK_ItemModel_ItemBrand");

                    b.Navigation("ItemBrand");
                });

            modelBuilder.Entity("KlangIT_V3.Models.ItemTypeToBrand", b =>
                {
                    b.HasOne("KlangIT_V3.Models.ItemBrand", "ItemBrand")
                        .WithMany("ItemTypeToBrands")
                        .HasForeignKey("ItemBrandId")
                        .IsRequired()
                        .HasConstraintName("FK_ItemTypeToBrand_ItemBrand");

                    b.HasOne("KlangIT_V3.Models.ItemType", "ItemType")
                        .WithMany("ItemTypeToBrands")
                        .HasForeignKey("ItemTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_ItemTypeToBrand_ItemType");

                    b.Navigation("ItemBrand");

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("KlangIT_V3.Models.Section", b =>
                {
                    b.HasOne("KlangIT_V3.Models.Department", "Department")
                        .WithMany("Sections")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Section_Department");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("KlangIT_V3.Models.StockLog", b =>
                {
                    b.HasOne("KlangIT_V3.Models.Item", "Item")
                        .WithMany("StockLogs")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_StockLog_Item");

                    b.HasOne("KlangIT_V3.Models.StockLogType", "StockLogType")
                        .WithMany("StockLogs")
                        .HasForeignKey("StockLogTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_StockLog_StockLogType");

                    b.Navigation("Item");

                    b.Navigation("StockLogType");
                });

            modelBuilder.Entity("KlangIT_V3.Models.Department", b =>
                {
                    b.Navigation("BorrowHistories");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("KlangIT_V3.Models.Item", b =>
                {
                    b.Navigation("BorrowHistories");

                    b.Navigation("StockLogs");
                });

            modelBuilder.Entity("KlangIT_V3.Models.ItemBrand", b =>
                {
                    b.Navigation("ItemModels");

                    b.Navigation("ItemTypeToBrands");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("KlangIT_V3.Models.ItemModel", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KlangIT_V3.Models.ItemStatus", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KlangIT_V3.Models.ItemType", b =>
                {
                    b.Navigation("ItemTypeToBrands");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("KlangIT_V3.Models.Section", b =>
                {
                    b.Navigation("BorrowHistories");
                });

            modelBuilder.Entity("KlangIT_V3.Models.StockLogType", b =>
                {
                    b.Navigation("StockLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
